apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stratos.fullname" . }}
  labels:
    {{- include "stratos.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - stratos.sh
    resources:
      - awsnodeclasses
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - stratos.sh
    resources:
      - awsnodeclasses/finalizers
      - nodepools/finalizers
    verbs:
      - update
  - apiGroups:
      - stratos.sh
    resources:
      - awsnodeclasses/status
      - nodepools/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - stratos.sh
    resources:
      - nodepools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
