/*
Copyright 2026 Stratos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package warmup

// scriptTemplate is the bash script template for pulling container images
// during instance warmup. The template generates a flat sequential script
// (not bash functions) with containerd readiness checks, ECR authentication,
// retry logic with exponential backoff, and policy-aware error handling.
const scriptTemplate = `#!/bin/bash
# Warmup script: pull and pin container images
# Generated by Stratos warmup script generator

# Wait for containerd socket
CONTAINERD_SOCKET="/run/containerd/containerd.sock"
SOCKET_TIMEOUT=60
elapsed=0

echo "Waiting for containerd socket..."
while [ ! -S "$CONTAINERD_SOCKET" ]; do
  if [ $elapsed -ge $SOCKET_TIMEOUT ]; then
    echo "ERROR: Containerd socket not ready after ${SOCKET_TIMEOUT}s"
    exit 1
  fi
  sleep 2
  elapsed=$((elapsed + 2))
done

# Verify containerd CRI is responding
echo "Verifying containerd is responding..."
until ctr version >/dev/null 2>&1; do
  if [ $elapsed -ge $SOCKET_TIMEOUT ]; then
    echo "ERROR: Containerd not responding after ${SOCKET_TIMEOUT}s"
    exit 1
  fi
  sleep 2
  elapsed=$((elapsed + 2))
done

echo "Containerd is ready"

{{- if .HasECRImages}}

# ECR authentication
echo "Fetching ECR authentication token for region {{.ECRRegion}}..."
ECR_PASSWORD=""
if command -v aws >/dev/null 2>&1; then
  if ECR_PASSWORD=$(aws ecr get-login-password --region {{.ECRRegion}} 2>&1); then
    echo "ECR authentication successful"
  else
    echo "WARNING: Failed to get ECR token: $ECR_PASSWORD"
    echo "Will attempt pulls without authentication (images may be public)"
    ECR_PASSWORD=""
  fi
else
  echo "WARNING: AWS CLI not found, skipping ECR authentication"
  echo "Will attempt pulls without authentication (images may be public)"
fi
{{- end}}

{{- if .IsBestEffort}}

# Image pull policy: BestEffort
echo "Image pull policy: BestEffort (failures logged but not fatal)"

{{- range .Images}}
# Pull {{.}}
pull_success=false
for attempt in 1 2 3; do
  start_time=$SECONDS
  echo "Pulling {{.}} (attempt $attempt/3)"

  {{- if $.HasECRImages}}
  # Check if this is an ECR image
  if echo "{{.}}" | grep -qE '\.dkr\.ecr\.[^.]+\.amazonaws\.com'; then
    if [ -n "$ECR_PASSWORD" ]; then
      if echo "$ECR_PASSWORD" | ctr -n k8s.io images pull --user "AWS:$ECR_PASSWORD" --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
        duration=$((SECONDS - start_time))
        echo "SUCCESS: Pulled {{.}} in ${duration}s"
        pull_success=true
        break
      fi
    else
      if ctr -n k8s.io images pull --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
        duration=$((SECONDS - start_time))
        echo "SUCCESS: Pulled {{.}} in ${duration}s"
        pull_success=true
        break
      fi
    fi
  else
    if ctr -n k8s.io images pull --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
      duration=$((SECONDS - start_time))
      echo "SUCCESS: Pulled {{.}} in ${duration}s"
      pull_success=true
      break
    fi
  fi
  {{- else}}
  if ctr -n k8s.io images pull --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
    duration=$((SECONDS - start_time))
    echo "SUCCESS: Pulled {{.}} in ${duration}s"
    pull_success=true
    break
  fi
  {{- end}}

  # Retry with exponential backoff
  if [ $attempt -lt 3 ]; then
    delay=$((2 ** (attempt - 1) * 2))  # 2s, 4s, 8s
    if [ $delay -gt 30 ]; then
      delay=30
    fi
    echo "RETRY: Failed to pull {{.}}, waiting ${delay}s"
    sleep $delay
  fi
done

if [ "$pull_success" = false ]; then
  echo "FAILURE: Could not pull {{.}} after 3 attempts (continuing anyway)"
fi
{{- end}}

echo "Image pre-pull completed (BestEffort)"
exit 0

{{- else}}

# Image pull policy: Required
echo "Image pull policy: Required (any failure will abort warmup)"

failure_count=0

{{- range .Images}}
# Pull {{.}}
pull_success=false
for attempt in 1 2 3; do
  start_time=$SECONDS
  echo "Pulling {{.}} (attempt $attempt/3)"

  {{- if $.HasECRImages}}
  # Check if this is an ECR image
  if echo "{{.}}" | grep -qE '\.dkr\.ecr\.[^.]+\.amazonaws\.com'; then
    if [ -n "$ECR_PASSWORD" ]; then
      if echo "$ECR_PASSWORD" | ctr -n k8s.io images pull --user "AWS:$ECR_PASSWORD" --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
        duration=$((SECONDS - start_time))
        echo "SUCCESS: Pulled {{.}} in ${duration}s"
        pull_success=true
        break
      fi
    else
      if ctr -n k8s.io images pull --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
        duration=$((SECONDS - start_time))
        echo "SUCCESS: Pulled {{.}} in ${duration}s"
        pull_success=true
        break
      fi
    fi
  else
    if ctr -n k8s.io images pull --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
      duration=$((SECONDS - start_time))
      echo "SUCCESS: Pulled {{.}} in ${duration}s"
      pull_success=true
      break
    fi
  fi
  {{- else}}
  if ctr -n k8s.io images pull --label io.cri-containerd.pinned=pinned "{{.}}" 2>&1; then
    duration=$((SECONDS - start_time))
    echo "SUCCESS: Pulled {{.}} in ${duration}s"
    pull_success=true
    break
  fi
  {{- end}}

  # Retry with exponential backoff
  if [ $attempt -lt 3 ]; then
    delay=$((2 ** (attempt - 1) * 2))  # 2s, 4s, 8s
    if [ $delay -gt 30 ]; then
      delay=30
    fi
    echo "RETRY: Failed to pull {{.}}, waiting ${delay}s"
    sleep $delay
  fi
done

if [ "$pull_success" = false ]; then
  echo "FAILURE: Could not pull {{.}} after 3 attempts"
  failure_count=$((failure_count + 1))
fi
{{- end}}

if [ $failure_count -gt 0 ]; then
  echo "ERROR: $failure_count image(s) failed to pull"
  exit 1
fi

echo "Image pre-pull completed (Required)"
exit 0

{{- end}}
`
