# NodePool using the selectors nodeclass
apiVersion: stratos.sh/v1alpha1
kind: NodePool
metadata:
  name: selectors
spec:
  # Pool configuration
  poolSize: 5
  minStandby: 2

  # Node template
  template:
    labels:
      workload: general
    nodeClassRef:
      kind: AWSNodeClass
      name: selectors
